global:
  scrape_interval: 5s     # Scrape metrics every 5 seconds for near real-time data
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'pharmasync-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']
